export const color_names = [
    // Pink colors
    "MediumVioletRed",
    "DeepPink",
    "PaleVioletRed",
    "HotPink",
    "LightPink",
    "Pink",

    // Red colors
    "DarkRed",
    "Red",
    "FireBrick",
    "Crimson",
    "IndianRed",
    "LightCoral",
    "Salmon",
    "DarkSalmon",
    "LightSalmon",

    // Orange colors
    "OrangeRed",
    "Tomato",
    "DarkOrange",
    "Coral",
    "Orange",

    // Yellow colors
    "DarkKhaki",
    "Gold",
    "Khaki",
    "PeachPuff",
    "Yellow",
    "PaleGoldenRod",
    "Moccasin",
    "PapayaWhip",
    "LightGoldenRodYellow",
    "LemonChiffon",
    "LightYellow",

    // Brown colors
    "Maroon",
    "Brown",
    "SaddleBrown",
    "Sienna",
    "Chocolate",
    "DarkGoldenRod",
    "Peru",
    "RosyBrown",
    "Goldenrod",
    "SandyBrown",
    "Tan",
    "BurlyWood",
    "Wheat",
    "NavajoWhite",
    "Bisque",
    "BlanchedAlmond",
    "Cornsilk",

    // Green colors
    "DarkGreen",
    "Green",
    "DarkOliveGreen",
    "ForestGreen",
    "SeaGreen",
    "Olive",
    "OliveDrab",
    "MediumSeaGreen",
    "LimeGreen",
    "Lime",
    "SpringGreen",
    "MediumSpringGreen",
    "DarkSeaGreen",
    "MediumAquaMarine",
    "YellowGreen",
    "LawnGreen",
    "Chartreuse",
    "LightGreen",
    "GreenYellow",
    "PaleGreen",

    // Cyan colors
    "Teal",
    "DarkCyan",
    "LightSeaGreen",
    "CadetBlue",
    "DarkTurquoise",
    "MediumTurquoise",
    "Turquoise",
    "Aqua",
    "Cyan",
    "Aquamarine",
    "PaleTurquoise",
    "LightCyan",

    // Blue colors
    "Navy",
    "DarkBlue",
    "MediumBlue",
    "Blue",
    "MidnightBlue",
    "RoyalBlue",
    "SteelBlue",
    "DodgerBlue",
    "DeepSkyBlue",
    "CornflowerBlue",
    "SkyBlue",
    "LightSkyBlue",
    "LightSteelBlue",
    "LightBlue",
    "PowderBlue",

    // Violet colors
    "Indigo",
    "Purple",
    "DarkMagenta",
    "DarkViolet",
    "DarkSlateBlue",
    "BlueViolet",
    "DarkOrchid",
    "Fuchsia",
    "Magenta",
    "SlateBlue",
    "MediumSlateBlue",
    "MediumOrchid",
    "MediumPurple",
    "Orchid",
    "Violet",
    "Plum",
    "Thistle",
    "Lavender",

    // White colors
    "MistyRose",
    "AntiqueWhite",
    "Linen",
    "WhiteSmoke",
    "LavenderBlush",
    "OldLace",
    "AliceBlue",
    "SeaShell",
    "GhostWhite",
    "HoneyDew",
    "FloralWhite",
    "Azure",
    "MintCream",
    "Snow",
    "Ivory",
    "White",

    // Gray colors
    "Black",
    "DarkSlateGray",
    "DimGray",
    "SlateGray",
    "Gray",
    "LightSlateGray",
    "DarkGray",
    "Silver",
    "LightGray",
    "Gainsboro",
];
